version: 2

registries:
  hcp-terraform:
    type: terraform-registry
    url: https://app.terraform.io
    token: ${{secrets.TF_API_TOKEN}}

updates:
  - package-ecosystem: "terraform"
    directory: "/terraform"
    registries:
      - hcp-terraform
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
