version: 2

registries:
  hcp-terraform:
    type: terraform-registry
    url: https://app.terraform.io
    token: ${{secrets.TF_API_TOKEN}}

updates:
  - package-ecosystem: "terraform"
    directory: "/terraform-core"
    registries:
      - hcp-terraform
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5

  - package-ecosystem: "terraform"
    directory: "/terraform-python"
    registries:
      - hcp-terraform
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5

  - package-ecosystem: "terraform"
    directory: "/terraform-managed-services"
    registries:
      - hcp-terraform
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5

  - package-ecosystem: "terraform"
    directory: "/terraform-aks-app"
    registries:
      - hcp-terraform
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5

  - package-ecosystem: "terraform"
    directory: "/terraform-shared-aks"
    registries:
      - hcp-terraform
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5

  - package-ecosystem: "terraform"
    directory: "/terraform-shared-plan"
    registries:
      - hcp-terraform
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5

  - package-ecosystem: "terraform"
    directory: "/terraform-prometheus"
    registries:
      - hcp-terraform
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5

  - package-ecosystem: "terraform"
    directory: "/terraform-runner"
    registries:
      - hcp-terraform
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
