# ──────────────────────────────────────────────────────────────────────────────
# Self-hosted GitHub Actions runner VM -- reduces reliance on GitHub-hosted
# ubuntu-latest minutes for the app repos' CI. Provisioning only: configuration
# (Docker, the runner agent, hardening) is handled separately by
# https://github.com/alderichoarau/azure-infra-ansible, not by this directory.
#
# Own directory/state: a personal convenience, not part of the quiz app's
# dependency chain, and only ever meant to be applied against prod (see
# README.md) -- the Simplon cohort's shared nonprod subscription has no use
# for a personal CI runner.
# ──────────────────────────────────────────────────────────────────────────────

locals {
  tags = merge(
    {
      managed_by  = "terraform"
      environment = var.environment
      owner       = var.owner
    },
    var.tags
  )
}

data "azurerm_resource_group" "rg" {
  name = var.resource_group_name
}

# ../terraform-core's outputs.tf exports vnet_name -- this stack's dedicated
# subnet attaches to it. Requires terraform-core to have been applied at
# least once already.
data "terraform_remote_state" "core" {
  backend = "remote"

  config = {
    organization = "alderic-hoarau"
    workspaces = {
      name = var.core_workspace_name
    }
  }
}

# ── Dedicated network for the runner VM ───────────────────────────────────────
# Own subnet rather than subnet-backend (../terraform-core): that one's NSG uses
# inline security_rule blocks, and mixing those with standalone
# azurerm_network_security_rule on the same NSG is unstable in practice (see
# ../terraform-prometheus's identical reasoning).
#
# 10.0.4.0/24: free in the VNet's 10.0.0.0/16 -- subnet-frontend (10.0.1.0/24),
# subnet-backend (10.0.2.0/24) and subnet-prometheus (10.0.3.0/24) are all
# already taken.

resource "azurerm_subnet" "runner" {
  name                 = "subnet-runner"
  resource_group_name  = data.azurerm_resource_group.rg.name
  virtual_network_name = data.terraform_remote_state.core.outputs.vnet_name
  address_prefixes     = ["10.0.4.0/24"]
}

resource "azurerm_network_security_group" "runner_vm" {
  # checkov:skip=CKV_AZURE_10: SSH restricted to a single /32 (the owner's own IP), not open
  name                = "nsg-runner-${var.owner}-tf"
  resource_group_name = data.azurerm_resource_group.rg.name
  location            = var.location
  tags                = local.tags

  security_rule {
    name                       = "Allow-SSH"
    priority                   = 100
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "22"
    source_address_prefix      = var.runner_admin_ip_cidr
    destination_address_prefix = "*"
  }

  # No explicit outbound rule: Azure's defaults are enough -- the runner only
  # ever needs outbound (polling GitHub, apt, downloading the runner binary).
}

resource "azurerm_subnet_network_security_group_association" "runner" {
  subnet_id                 = azurerm_subnet.runner.id
  network_security_group_id = azurerm_network_security_group.runner_vm.id
}

resource "azurerm_public_ip" "runner_vm" {
  # checkov:skip=CKV_AZURE_59: public IP needed for SSH admin access, restricted to one /32 by the NSG above
  name                = "pip-runner-${var.owner}-tf"
  resource_group_name = data.azurerm_resource_group.rg.name
  location            = var.location
  allocation_method   = "Static"
  sku                 = "Standard"
  tags                = local.tags
}

resource "azurerm_network_interface" "runner_vm" {
  # checkov:skip=CKV_AZURE_119: public IP needed for SSH admin access, restricted to one /32 by the NSG above
  name                = "nic-runner-${var.owner}-tf"
  resource_group_name = data.azurerm_resource_group.rg.name
  location            = var.location
  tags                = local.tags

  ip_configuration {
    name                          = "internal"
    subnet_id                     = azurerm_subnet.runner.id
    private_ip_address_allocation = "Dynamic"
    public_ip_address_id          = azurerm_public_ip.runner_vm.id
  }
}

resource "azurerm_network_interface_security_group_association" "runner_vm" {
  network_interface_id      = azurerm_network_interface.runner_vm.id
  network_security_group_id = azurerm_network_security_group.runner_vm.id
}

# ── SSH key, generated by Terraform ───────────────────────────────────────────
# Used both for the owner's own SSH admin access and by azure-infra-ansible's
# playbook (runner_ssh_private_key output).
resource "tls_private_key" "runner_vm" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

# ── Runner VM ──────────────────────────────────────────────────────────────────
resource "azurerm_linux_virtual_machine" "runner" {
  # checkov:skip=CKV_AZURE_149: Trusted Launch not needed for this VM
  # checkov:skip=CKV_AZURE_50: antimalware extension not needed for this VM
  name                  = "vm-runner-${var.owner}-tf"
  resource_group_name   = data.azurerm_resource_group.rg.name
  location              = var.location
  size                  = var.runner_vm_size
  admin_username        = "azureuser"
  network_interface_ids = [azurerm_network_interface.runner_vm.id]
  tags                  = local.tags

  admin_ssh_key {
    username   = "azureuser"
    public_key = tls_private_key.runner_vm.public_key_openssh
  }

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }

  source_image_reference {
    publisher = "Canonical"
    offer     = "0001-com-ubuntu-server-jammy"
    sku       = "22_04-lts"
    version   = "latest"
  }

  # No custom_data: azure-infra-ansible's playbook does all the configuration,
  # deliberately kept out of Terraform's remit here.
}
